### ISSUE TITLE
Database situation

### ISSUE THREAD

**Issue by Hasaniafmbegin** [sajalagrawal/LifestyleStore#4]
Hi sajalgrawl I just found your web application and it looks great. You've done some phenomenal work. I am trying to use the sign up feature which by extension includes the loginfeature and the buy products feature, etc and when ever i click on the sign up buton i keep geting this message. 

Warning: mysqli_connect(): (HY000/1045): Access denied for user 'id2538044_sajalagrawal'@'localhost' (using password: YES) in C:\xampp\htdocs\lifestore\LifestyleStore-master\LifestyleStore\connection.php on line 2

Fatal error: Uncaught TypeError: mysqli_error(): Argument #1 ($mysql) must be of type mysqli, bool given in C:\xampp\htdocs\lifestore\LifestyleStore-master\LifestyleStore\connection.php:2 Stack trace: #0 C:\xampp\htdocs\lifestore\LifestyleStore-master\LifestyleStore\connection.php(2): mysqli_error(false) #1 C:\xampp\htdocs\lifestore\LifestyleStore-master\LifestyleStore\signup.php(2): require('C:\\xampp\\htdocs...') #2 {main} thrown in C:\xampp\htdocs\lifestore\LifestyleStore-master\LifestyleStore\connection.php on line 2

I have tried to fix the problem using youtube videos but I can not see, to get it to work. I was wondering if you can help me. Just to let you know I am not using wamp instead I am using XAMMP for my database. Could you please help me and maybe direct me to a youtube video that could be useful. Also this is not a major issue but do you know how I can change the image of the homepage. 

Best regards Hasan Ali.

**Comment by Hanenlouati** [comment]
same issue

**Comment by adil77uk** [comment]
Fixed
